{"name": "test_login_02", "status": "passed", "description": "错误的用户名为root", "start": 1584783241056, "stop": 1584783241396, "uuid": "add6897a-4a20-493e-8095-57d669474e45", "historyId": "5f486bc8ff6b25a3112ca15d27b87a1e", "testCaseId": "21988ccf8fa85b03d692fdd20c0f30aa", "fullName": "case.mul_form_data.test_login.TestLogin#test_login_02", "labels": [{"name": "feature", "value": "登录的接口"}, {"name": "story", "value": "传入错误的用户名,正确的密码"}, {"name": "parentSuite", "value": "case.mul_form_data"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "S28RZMS68F89XOJ"}, {"name": "thread", "value": "6748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.mul_form_data.test_login"}]}